// Generated by Wrangler by running `wrangler types`

interface Env {
	BETTER_AUTH_SECRET: string;
	BETTER_AUTH_URL: string;
	TURNSTILE_SECRET: string;
	TURSO_AUTH_TOKEN: string;
	TURSO_DATABASE_URL: string;
	GITHUB_CLIENT_ID: string;
	GITHUB_CLIENT_SECRET: string;
}
